name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/checkout@v3
        with:
          path: data
          ref: data
        continue-on-error: true
      - uses: jdx/mise-action@v2
      - uses: ./.github/actions/cache-pnpm-store
      - run: pnpm install --frozen-lockfile
      - run: pnpm export
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
          cname: ${{ github.event.repository.name }}